name: Detect Secrets

on: [push, pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    container: python:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Yelp's detect secrets
      run: |
        apt-get update && apt-get install -y jq
        pip install yq
        pip install detect-secrets==$(yq r .pre-commit-config.yaml repos[0].rev)

    - name: Detect potential secrets
      run: find -type f -not -path './.git/*' -printf '%P\n' | xargs detect-secrets-hook --baseline .secrets.baseline
